---
 
  #
  # Install APT Packages
  #
  
  - name: Update APT index
    sudo: yes
    apt: update_cache=yes

  - name: Install basic APT packages
    sudo: yes
    apt: pkg={{item}} state=latest
    with_items:
    - vim
    - vim-scripts
    - bzip2
    - p7zip-full
    - screen
    - less
    - wget
    - curl
    - rsync
    - git
    - mercurial
    - htop
    - build-essential
    - zlib1g-dev
    - libxslt1-dev
    - libxml2-dev
    - python-dev
    - python-virtualenv
    - python-setuptools

  #
  # Setup user's profile and basic directories
  #

  - name: Create a Bash profile
    template: src=etc/user-profile dest=~/.profile mode=0600

  - name: Create a user-local workspace directory
    file: path=~/workspace state=directory mode=0755
  
  #
  # Create a Python virtualenv for user
  #
  
  - name: Create Python virtualenv
    shell: /usr/bin/virtualenv ~/pyenv creates=~/pyenv

  - name: Install newest version of pip
    pip:  name=pip extra_args='--upgrade' virtualenv=~/pyenv
  
  - name: Install basic Python packages into virtualenv.
    pip: name={{item}} virtualenv=~/pyenv
    with_items:
    - 'argparse'
    - 'pytz'
    - 'isodate'
    - 'ipython'
    - 'jinja2'
    - 'genshi'
    - 'lxml'
    - 'pudb'
    - 'nose'
    - 'pep8'

  #
  # Configure Git client
  #

  - name: Provide bash completion for git
    sudo: yes
    get_url: url={{git_completion_script}} dest=/etc/bash_completion.d/git force=no mode=0644


  #
  # More ...
  #


